[pytest]
pythonpath =
    ../..
    ..
addopts =
    --cov=backend
    --cov-config=.coveragerc
    --cov-report=term-missing
markers =
    integration: tests that perform external I/O with Alpaca, AWS
