export const countryOptions = [
  { value: "USA", label: "United States" },
  { value: "CAN", label: "Canada" },
  { value: "MEX", label: "Mexico" },
  { value: "GBR", label: "United Kingdom" },
  { value: "AUS", label: "Australia" },
  { value: "AUT", label: "Austria" },
  { value: "BEL", label: "Belgium" },
  { value: "BRA", label: "Brazil" },
  { value: "CHL", label: "Chile" },
  { value: "COL", label: "Colombia" },
  { value: "CRI", label: "Costa Rica" },
  { value: "CZE", label: "Czechia" },
  { value: "DNK", label: "Denmark" },
  { value: "FIN", label: "Finland" },
  { value: "FRA", label: "France" },
  { value: "DEU", label: "Germany" },
  { value: "GRC", label: "Greece" },
  { value: "HKG", label: "Hong Kong" },
  { value: "HUN", label: "Hungary" },
  { value: "IND", label: "India" },
  { value: "IDN", label: "Indonesia" },
  { value: "IRL", label: "Ireland" },
  { value: "ISR", label: "Israel" },
  { value: "ITA", label: "Italy" },
  { value: "JPN", label: "Japan" },
  { value: "LUX", label: "Luxembourg" },
  { value: "MYS", label: "Malaysia" },
  { value: "NLD", label: "Netherlands" },
  { value: "NZL", label: "New Zealand" },
  { value: "NOR", label: "Norway" },
  { value: "PER", label: "Peru" },
  { value: "PHL", label: "Philippines" },
  { value: "POL", label: "Poland" },
  { value: "PRT", label: "Portugal" },
  { value: "SGP", label: "Singapore" },
  { value: "ZAF", label: "South Africa" },
  { value: "KOR", label: "South Korea" },
  { value: "ESP", label: "Spain" },
  { value: "SWE", label: "Sweden" },
  { value: "CHE", label: "Switzerland" },
  { value: "TWN", label: "Taiwan" },
  { value: "THA", label: "Thailand" },
  { value: "ARE", label: "United Arab Emirates" },
  { value: "URY", label: "Uruguay" },
];
